FROM openjdk:17-jdk

WORKDIR /app

COPY target/spring-boot-data-jpa-0.0.1-SNAPSHOT.jar /app/spring-boot-data-jpa-0.0.1-SNAPSHOT.jar

EXPOSE 8000

CMD [ "java" , "-jar" , "spring-boot-data-jpa-0.0.1-SNAPSHOT.jar" ]